services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - staticfiles_volume:/app/staticfiles:ro
    depends_on:
      - app

  app:
    build: .
    container_name: django_app
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - staticfiles_volume:/app/staticfiles
    environment:
      - PYTHONPATH=/app
    depends_on:
      - db
      - redis
    env_file: .env

  db:
    image: postgres:17
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env

  redis:
    image: redis:7
    container_name: redis_cache

  celery_worker:
    build: .
    container_name: celery_worker
    command: celery -A core worker -l info
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    depends_on:
      - redis
      - app
    env_file: .env

  celery_beat:
    build: .
    container_name: celery_beat
    command: celery -A core beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    depends_on:
      - redis
      - app
    env_file: .env
  
  flower:
    build: .
    container_name: flower_monitor
    command: celery -A core flower
    ports:
      - "5555:5555"
    environment:
      - PYTHONPATH=/app
    depends_on:
      - redis
      - app
    env_file: .env

volumes:
  postgres_data:
  staticfiles_volume: